### ISSUE TITLE
Problem with the url

### ISSUE THREAD

**Issue by marcemira** [unwiredbrain/ember-cli-piwik#2]
Hello @unwiredbrain, the problem is that I have a local piwiki that I set like this:

``` json
url: 'localhost/piwik'
```

And then it generates an html like this:

``` html
<script src="//localhost/piwik/piwik.js" async defer></script>
```

which won't work because my app runs at https, which is not my localhost piwik's case.
So then I tried forcing the http like this:

``` json
url: 'http://localhost/piwik'
```

And the resulting html was:

``` html
<script src="//http://localhost/piwik/piwik.js" async="" defer=""></script>
```

Am I doing something very wrong or do I need to try using different domain?

Thanks!

**Comment by unwiredbrain** [comment]
Thanks for the heads-up @marcemira, that's a use case I haven't considered.

Oddly enough, even [Piwik’s “official” tracking code behaves the same way](http://developer.piwik.org/guides/tracking-javascript-guide)—if the `document.location.protocol` of the page loading the tracker is `https:` prepend `https:` to the Piwik server URL, otherwise prepend `http:`

My approach is similar: it uses a [network-path reference](http://tools.ietf.org/html/rfc3986#section-4.2) (informally known as “protocol-relative URL” or “schema-less URL”) that achieves the same result with less code and thus less moving parts. Interestingly enough, [Google Analytics](https://developers.google.com/analytics/devguides/collection/analyticsjs/), [Mixpanel](https://mixpanel.com/help/reference/javascript) and many more vendors that provide 3rd-party injectable code use the same technique.

Unfortunately, this doesn't play well in at least two scenarios:
1. when loading a page served from a local filesystem path – `file:///home/foo/bar.html`
2. when the Piwik server is configured to respond to either HTTP or HTTPS requests only

I'm gonna remove the network-path reference logic and let the addon consumer (you) specify what to use.

This will also give addon consumers more flexibility when dealing with different environments: an absolute URI could be preferred for development and test environments while using a network-path reference for the production one.

**Comment by marcemira** [comment]
@unwiredbrain Awesome!, thank you :+1:
